version: "2"
services:

  novnc:
    build: build
    environment:
      # Adjust to your screen size
      - XDISPLAY_WIDTH=1600
      - XDISPLAY_HEIGHT=968
      - XDISPLAY_DEPTH=16
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    ports:
      - "8080:8080"
    volumes:
      - data:/workdir
    networks:
      - x11

volumes:
  data:
    driver: local

networks:
  x11:
